# Copyright 2020 Espressif Systems (Shanghai) PTE LTD
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloud.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cloud.proto',
  package='cloud',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x63loud.proto\x12\x05\x63loud\"5\n\x10\x43mdGetSetDetails\x12\x0e\n\x06UserID\x18\x01 \x01(\t\x12\x11\n\tSecretKey\x18\x02 \x01(\t\"S\n\x11RespGetSetDetails\x12(\n\x06Status\x18\x01 \x01(\x0e\x32\x18.cloud.CloudConfigStatus\x12\x14\n\x0c\x44\x65viceSecret\x18\x02 \x01(\t\"\xb9\x01\n\x12\x43loudConfigPayload\x12&\n\x03msg\x18\x01 \x01(\x0e\x32\x19.cloud.CloudConfigMsgType\x12\x36\n\x13\x63md_get_set_details\x18\n \x01(\x0b\x32\x17.cloud.CmdGetSetDetailsH\x00\x12\x38\n\x14resp_get_set_details\x18\x0b \x01(\x0b\x32\x18.cloud.RespGetSetDetailsH\x00\x42\t\n\x07payload*D\n\x11\x43loudConfigStatus\x12\x0b\n\x07Success\x10\x00\x12\x10\n\x0cInvalidParam\x10\x01\x12\x10\n\x0cInvalidState\x10\x02*I\n\x12\x43loudConfigMsgType\x12\x18\n\x14TypeCmdGetSetDetails\x10\x00\x12\x19\n\x15TypeRespGetSetDetails\x10\x01\x62\x06proto3')
)

_CLOUDCONFIGSTATUS = _descriptor.EnumDescriptor(
  name='CloudConfigStatus',
  full_name='cloud.CloudConfigStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Success', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InvalidParam', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InvalidState', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=350,
  serialized_end=418,
)
_sym_db.RegisterEnumDescriptor(_CLOUDCONFIGSTATUS)

CloudConfigStatus = enum_type_wrapper.EnumTypeWrapper(_CLOUDCONFIGSTATUS)
_CLOUDCONFIGMSGTYPE = _descriptor.EnumDescriptor(
  name='CloudConfigMsgType',
  full_name='cloud.CloudConfigMsgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TypeCmdGetSetDetails', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TypeRespGetSetDetails', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=420,
  serialized_end=493,
)
_sym_db.RegisterEnumDescriptor(_CLOUDCONFIGMSGTYPE)

CloudConfigMsgType = enum_type_wrapper.EnumTypeWrapper(_CLOUDCONFIGMSGTYPE)
Success = 0
InvalidParam = 1
InvalidState = 2
TypeCmdGetSetDetails = 0
TypeRespGetSetDetails = 1



_CMDGETSETDETAILS = _descriptor.Descriptor(
  name='CmdGetSetDetails',
  full_name='cloud.CmdGetSetDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserID', full_name='cloud.CmdGetSetDetails.UserID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SecretKey', full_name='cloud.CmdGetSetDetails.SecretKey', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=75,
)


_RESPGETSETDETAILS = _descriptor.Descriptor(
  name='RespGetSetDetails',
  full_name='cloud.RespGetSetDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Status', full_name='cloud.RespGetSetDetails.Status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DeviceSecret', full_name='cloud.RespGetSetDetails.DeviceSecret', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=160,
)


_CLOUDCONFIGPAYLOAD = _descriptor.Descriptor(
  name='CloudConfigPayload',
  full_name='cloud.CloudConfigPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='cloud.CloudConfigPayload.msg', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cmd_get_set_details', full_name='cloud.CloudConfigPayload.cmd_get_set_details', index=1,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resp_get_set_details', full_name='cloud.CloudConfigPayload.resp_get_set_details', index=2,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='cloud.CloudConfigPayload.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=163,
  serialized_end=348,
)

_RESPGETSETDETAILS.fields_by_name['Status'].enum_type = _CLOUDCONFIGSTATUS
_CLOUDCONFIGPAYLOAD.fields_by_name['msg'].enum_type = _CLOUDCONFIGMSGTYPE
_CLOUDCONFIGPAYLOAD.fields_by_name['cmd_get_set_details'].message_type = _CMDGETSETDETAILS
_CLOUDCONFIGPAYLOAD.fields_by_name['resp_get_set_details'].message_type = _RESPGETSETDETAILS
_CLOUDCONFIGPAYLOAD.oneofs_by_name['payload'].fields.append(
  _CLOUDCONFIGPAYLOAD.fields_by_name['cmd_get_set_details'])
_CLOUDCONFIGPAYLOAD.fields_by_name['cmd_get_set_details'].containing_oneof = _CLOUDCONFIGPAYLOAD.oneofs_by_name['payload']
_CLOUDCONFIGPAYLOAD.oneofs_by_name['payload'].fields.append(
  _CLOUDCONFIGPAYLOAD.fields_by_name['resp_get_set_details'])
_CLOUDCONFIGPAYLOAD.fields_by_name['resp_get_set_details'].containing_oneof = _CLOUDCONFIGPAYLOAD.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['CmdGetSetDetails'] = _CMDGETSETDETAILS
DESCRIPTOR.message_types_by_name['RespGetSetDetails'] = _RESPGETSETDETAILS
DESCRIPTOR.message_types_by_name['CloudConfigPayload'] = _CLOUDCONFIGPAYLOAD
DESCRIPTOR.enum_types_by_name['CloudConfigStatus'] = _CLOUDCONFIGSTATUS
DESCRIPTOR.enum_types_by_name['CloudConfigMsgType'] = _CLOUDCONFIGMSGTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CmdGetSetDetails = _reflection.GeneratedProtocolMessageType('CmdGetSetDetails', (_message.Message,), dict(
  DESCRIPTOR = _CMDGETSETDETAILS,
  __module__ = 'cloud_pb2'
  # @@protoc_insertion_point(class_scope:cloud.CmdGetSetDetails)
  ))
_sym_db.RegisterMessage(CmdGetSetDetails)

RespGetSetDetails = _reflection.GeneratedProtocolMessageType('RespGetSetDetails', (_message.Message,), dict(
  DESCRIPTOR = _RESPGETSETDETAILS,
  __module__ = 'cloud_pb2'
  # @@protoc_insertion_point(class_scope:cloud.RespGetSetDetails)
  ))
_sym_db.RegisterMessage(RespGetSetDetails)

CloudConfigPayload = _reflection.GeneratedProtocolMessageType('CloudConfigPayload', (_message.Message,), dict(
  DESCRIPTOR = _CLOUDCONFIGPAYLOAD,
  __module__ = 'cloud_pb2'
  # @@protoc_insertion_point(class_scope:cloud.CloudConfigPayload)
  ))
_sym_db.RegisterMessage(CloudConfigPayload)


# @@protoc_insertion_point(module_scope)
