/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: esp_rmaker_prov_local_ctrl.proto */

#ifndef PROTOBUF_C_esp_5frmaker_5fprov_5flocal_5fctrl_2eproto__INCLUDED
#define PROTOBUF_C_esp_5frmaker_5fprov_5flocal_5fctrl_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct RmakerProvLocalCtrl__PayloadBuf RmakerProvLocalCtrl__PayloadBuf;
typedef struct RmakerProvLocalCtrl__CmdGetData RmakerProvLocalCtrl__CmdGetData;
typedef struct RmakerProvLocalCtrl__RespGetData RmakerProvLocalCtrl__RespGetData;
typedef struct RmakerProvLocalCtrl__RMakerLocalCtrlPayload RmakerProvLocalCtrl__RMakerLocalCtrlPayload;


/* --- enums --- */

typedef enum _RmakerProvLocalCtrl__RMakerLocalCtrlStatus {
  RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_STATUS__Success = 0,
  RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_STATUS__Fail = 1,
  RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_STATUS__InvalidParam = 2,
  RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_STATUS__NoMemory = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_STATUS)
} RmakerProvLocalCtrl__RMakerLocalCtrlStatus;
typedef enum _RmakerProvLocalCtrl__RMakerLocalCtrlDataType {
  RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_DATA_TYPE__TypeParams = 0,
  RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_DATA_TYPE__TypeConfig = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_DATA_TYPE)
} RmakerProvLocalCtrl__RMakerLocalCtrlDataType;
typedef enum _RmakerProvLocalCtrl__RMakerLocalCtrlMsgType {
  RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_MSG_TYPE__TypeCmdGetData = 0,
  RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_MSG_TYPE__TypeRespGetData = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_MSG_TYPE)
} RmakerProvLocalCtrl__RMakerLocalCtrlMsgType;

/* --- messages --- */

struct  RmakerProvLocalCtrl__PayloadBuf
{
  ProtobufCMessage base;
  uint32_t offset;
  ProtobufCBinaryData payload;
  uint32_t totallen;
};
#define RMAKER_PROV_LOCAL_CTRL__PAYLOAD_BUF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rmaker_prov_local_ctrl__payload_buf__descriptor) \
, 0, {0,NULL}, 0 }


/*
 * Command to get data (params or config) - contains offset to request next chunk 
 */
struct  RmakerProvLocalCtrl__CmdGetData
{
  ProtobufCMessage base;
  RmakerProvLocalCtrl__RMakerLocalCtrlDataType datatype;
  uint32_t offset;
  /*
   * Optional timestamp for signed response 
   */
  int64_t timestamp;
  /*
   * Flag to indicate if timestamp is provided (since 0 is a valid timestamp) 
   */
  protobuf_c_boolean hastimestamp;
};
#define RMAKER_PROV_LOCAL_CTRL__CMD_GET_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rmaker_prov_local_ctrl__cmd_get_data__descriptor) \
, RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_DATA_TYPE__TypeParams, 0, 0, 0 }


/*
 * Response with data (params or config) 
 */
struct  RmakerProvLocalCtrl__RespGetData
{
  ProtobufCMessage base;
  RmakerProvLocalCtrl__RMakerLocalCtrlStatus status;
  RmakerProvLocalCtrl__PayloadBuf *buf;
};
#define RMAKER_PROV_LOCAL_CTRL__RESP_GET_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rmaker_prov_local_ctrl__resp_get_data__descriptor) \
, RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_STATUS__Success, NULL }


typedef enum {
  RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_PAYLOAD__PAYLOAD__NOT_SET = 0,
  RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_PAYLOAD__PAYLOAD_CMD_GET_DATA = 10,
  RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_PAYLOAD__PAYLOAD_RESP_GET_DATA = 11
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_PAYLOAD__PAYLOAD__CASE)
} RmakerProvLocalCtrl__RMakerLocalCtrlPayload__PayloadCase;

struct  RmakerProvLocalCtrl__RMakerLocalCtrlPayload
{
  ProtobufCMessage base;
  RmakerProvLocalCtrl__RMakerLocalCtrlMsgType msg;
  RmakerProvLocalCtrl__RMakerLocalCtrlPayload__PayloadCase payload_case;
  union {
    RmakerProvLocalCtrl__CmdGetData *cmdgetdata;
    RmakerProvLocalCtrl__RespGetData *respgetdata;
  };
};
#define RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_PAYLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rmaker_prov_local_ctrl__rmaker_local_ctrl_payload__descriptor) \
, RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_MSG_TYPE__TypeCmdGetData, RMAKER_PROV_LOCAL_CTRL__RMAKER_LOCAL_CTRL_PAYLOAD__PAYLOAD__NOT_SET, {0} }


/* RmakerProvLocalCtrl__PayloadBuf methods */
void   rmaker_prov_local_ctrl__payload_buf__init
                     (RmakerProvLocalCtrl__PayloadBuf         *message);
size_t rmaker_prov_local_ctrl__payload_buf__get_packed_size
                     (const RmakerProvLocalCtrl__PayloadBuf   *message);
size_t rmaker_prov_local_ctrl__payload_buf__pack
                     (const RmakerProvLocalCtrl__PayloadBuf   *message,
                      uint8_t             *out);
size_t rmaker_prov_local_ctrl__payload_buf__pack_to_buffer
                     (const RmakerProvLocalCtrl__PayloadBuf   *message,
                      ProtobufCBuffer     *buffer);
RmakerProvLocalCtrl__PayloadBuf *
       rmaker_prov_local_ctrl__payload_buf__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rmaker_prov_local_ctrl__payload_buf__free_unpacked
                     (RmakerProvLocalCtrl__PayloadBuf *message,
                      ProtobufCAllocator *allocator);
/* RmakerProvLocalCtrl__CmdGetData methods */
void   rmaker_prov_local_ctrl__cmd_get_data__init
                     (RmakerProvLocalCtrl__CmdGetData         *message);
size_t rmaker_prov_local_ctrl__cmd_get_data__get_packed_size
                     (const RmakerProvLocalCtrl__CmdGetData   *message);
size_t rmaker_prov_local_ctrl__cmd_get_data__pack
                     (const RmakerProvLocalCtrl__CmdGetData   *message,
                      uint8_t             *out);
size_t rmaker_prov_local_ctrl__cmd_get_data__pack_to_buffer
                     (const RmakerProvLocalCtrl__CmdGetData   *message,
                      ProtobufCBuffer     *buffer);
RmakerProvLocalCtrl__CmdGetData *
       rmaker_prov_local_ctrl__cmd_get_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rmaker_prov_local_ctrl__cmd_get_data__free_unpacked
                     (RmakerProvLocalCtrl__CmdGetData *message,
                      ProtobufCAllocator *allocator);
/* RmakerProvLocalCtrl__RespGetData methods */
void   rmaker_prov_local_ctrl__resp_get_data__init
                     (RmakerProvLocalCtrl__RespGetData         *message);
size_t rmaker_prov_local_ctrl__resp_get_data__get_packed_size
                     (const RmakerProvLocalCtrl__RespGetData   *message);
size_t rmaker_prov_local_ctrl__resp_get_data__pack
                     (const RmakerProvLocalCtrl__RespGetData   *message,
                      uint8_t             *out);
size_t rmaker_prov_local_ctrl__resp_get_data__pack_to_buffer
                     (const RmakerProvLocalCtrl__RespGetData   *message,
                      ProtobufCBuffer     *buffer);
RmakerProvLocalCtrl__RespGetData *
       rmaker_prov_local_ctrl__resp_get_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rmaker_prov_local_ctrl__resp_get_data__free_unpacked
                     (RmakerProvLocalCtrl__RespGetData *message,
                      ProtobufCAllocator *allocator);
/* RmakerProvLocalCtrl__RMakerLocalCtrlPayload methods */
void   rmaker_prov_local_ctrl__rmaker_local_ctrl_payload__init
                     (RmakerProvLocalCtrl__RMakerLocalCtrlPayload         *message);
size_t rmaker_prov_local_ctrl__rmaker_local_ctrl_payload__get_packed_size
                     (const RmakerProvLocalCtrl__RMakerLocalCtrlPayload   *message);
size_t rmaker_prov_local_ctrl__rmaker_local_ctrl_payload__pack
                     (const RmakerProvLocalCtrl__RMakerLocalCtrlPayload   *message,
                      uint8_t             *out);
size_t rmaker_prov_local_ctrl__rmaker_local_ctrl_payload__pack_to_buffer
                     (const RmakerProvLocalCtrl__RMakerLocalCtrlPayload   *message,
                      ProtobufCBuffer     *buffer);
RmakerProvLocalCtrl__RMakerLocalCtrlPayload *
       rmaker_prov_local_ctrl__rmaker_local_ctrl_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rmaker_prov_local_ctrl__rmaker_local_ctrl_payload__free_unpacked
                     (RmakerProvLocalCtrl__RMakerLocalCtrlPayload *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*RmakerProvLocalCtrl__PayloadBuf_Closure)
                 (const RmakerProvLocalCtrl__PayloadBuf *message,
                  void *closure_data);
typedef void (*RmakerProvLocalCtrl__CmdGetData_Closure)
                 (const RmakerProvLocalCtrl__CmdGetData *message,
                  void *closure_data);
typedef void (*RmakerProvLocalCtrl__RespGetData_Closure)
                 (const RmakerProvLocalCtrl__RespGetData *message,
                  void *closure_data);
typedef void (*RmakerProvLocalCtrl__RMakerLocalCtrlPayload_Closure)
                 (const RmakerProvLocalCtrl__RMakerLocalCtrlPayload *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    rmaker_prov_local_ctrl__rmaker_local_ctrl_status__descriptor;
extern const ProtobufCEnumDescriptor    rmaker_prov_local_ctrl__rmaker_local_ctrl_data_type__descriptor;
extern const ProtobufCEnumDescriptor    rmaker_prov_local_ctrl__rmaker_local_ctrl_msg_type__descriptor;
extern const ProtobufCMessageDescriptor rmaker_prov_local_ctrl__payload_buf__descriptor;
extern const ProtobufCMessageDescriptor rmaker_prov_local_ctrl__cmd_get_data__descriptor;
extern const ProtobufCMessageDescriptor rmaker_prov_local_ctrl__resp_get_data__descriptor;
extern const ProtobufCMessageDescriptor rmaker_prov_local_ctrl__rmaker_local_ctrl_payload__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_esp_5frmaker_5fprov_5flocal_5fctrl_2eproto__INCLUDED */
